import React from "react";
import { Bar } from "react-chartjs-2";
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend } from "chart.js";

ChartJS.register(CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend);

const EntrepreneurshipChart = () => {
  const data = {
    labels: ["Tech", "Retail", "Healthcare", "Food Services", "Other Sectors"],
    datasets: [
      {
        label: "Businesses Founded by Immigrants",
        data: [28, 22, 18, 15, 17], // Percentage of immigrant-owned businesses by industry
        backgroundColor: ["#1E88E5", "#FDD835", "#43A047", "#E53935", "#8E24AA"],
      },
      {
        label: "Jobs Created (Thousands)",
        data: [1500, 1200, 800, 600, 750], // Jobs generated by immigrant businesses (in thousands)
        backgroundColor: ["#64B5F6", "#FFF176", "#81C784", "#EF5350", "#BA68C8"],
      },
    ],
  };

  const options = {
    plugins: {
      title: {
        display: true,
        text: "🚀 Immigrant Entrepreneurship & Job Creation (2024)",
      },
      tooltip: {
        callbacks: {
          label: function (tooltipItem) {
            return tooltipItem.dataset.label === "Businesses Founded by Immigrants"
              ? `${tooltipItem.raw}% of businesses in this industry are immigrant-owned`
              : `${tooltipItem.raw}K jobs created`;
          },
        },
      },
    },
  };

  return <Bar data={data} options={options} />;
};

export default EntrepreneurshipChart;
